title: Products

sections:
  drafts:
    headline: Drafts
    type: pages
    layout: list
    template: product
    info: "{{ page.name }}"
    help: These products are not published yet
    status: drafts
    image:
      ratio: 4/5
      cover: true

  published:
    headline: Published
    type: pages
    layout: cards
    template: product
    info: "{{ page.name }}"
    status: published
    image:
      ratio: 4/5
      cover: true
